package calculatrice;

/**
* calculatrice/badParamHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculatrice.idl
* vendredi 7 juin 2013 15 h 07 CEST
*/

public final class badParamHolder implements org.omg.CORBA.portable.Streamable
{
  public calculatrice.badParam value = null;

  public badParamHolder ()
  {
  }

  public badParamHolder (calculatrice.badParam initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calculatrice.badParamHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calculatrice.badParamHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calculatrice.badParamHelper.type ();
  }

}
