package calculatrice;


/**
* calculatrice/CalculatriceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculatrice.idl
* vendredi 7 juin 2013 15 h 07 CEST
*/

public interface CalculatriceOperations 
{
  org.omg.CORBA.Any addition (org.omg.CORBA.Any nb1, org.omg.CORBA.Any nb2) throws calculatrice.badParam;
  org.omg.CORBA.Any sub (org.omg.CORBA.Any nb1, org.omg.CORBA.Any nb2) throws calculatrice.badParam;
  org.omg.CORBA.Any mult (org.omg.CORBA.Any nb1, org.omg.CORBA.Any nb2) throws calculatrice.badParam;
  org.omg.CORBA.Any div (org.omg.CORBA.Any nb1, org.omg.CORBA.Any nb2) throws calculatrice.badParam, calculatrice.divZero;
} // interface CalculatriceOperations
