package calculatrice;


/**
* calculatrice/CalculatriceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculatrice.idl
* vendredi 7 juin 2013 15 h 07 CEST
*/

abstract public class CalculatriceHelper
{
  private static String  _id = "IDL:calculatrice/Calculatrice:1.0";

  public static void insert (org.omg.CORBA.Any a, calculatrice.Calculatrice that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static calculatrice.Calculatrice extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (calculatrice.CalculatriceHelper.id (), "Calculatrice");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static calculatrice.Calculatrice read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CalculatriceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, calculatrice.Calculatrice value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static calculatrice.Calculatrice narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof calculatrice.Calculatrice)
      return (calculatrice.Calculatrice)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      calculatrice._CalculatriceStub stub = new calculatrice._CalculatriceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static calculatrice.Calculatrice unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof calculatrice.Calculatrice)
      return (calculatrice.Calculatrice)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      calculatrice._CalculatriceStub stub = new calculatrice._CalculatriceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
