package calculatrice;

/**
* calculatrice/CalculatriceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculatrice.idl
* vendredi 7 juin 2013 15 h 07 CEST
*/

public final class CalculatriceHolder implements org.omg.CORBA.portable.Streamable
{
  public calculatrice.Calculatrice value = null;

  public CalculatriceHolder ()
  {
  }

  public CalculatriceHolder (calculatrice.Calculatrice initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calculatrice.CalculatriceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calculatrice.CalculatriceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calculatrice.CalculatriceHelper.type ();
  }

}
