package calculatrice;

/**
* calculatrice/divZeroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculatrice.idl
* vendredi 7 juin 2013 15 h 07 CEST
*/

public final class divZeroHolder implements org.omg.CORBA.portable.Streamable
{
  public calculatrice.divZero value = null;

  public divZeroHolder ()
  {
  }

  public divZeroHolder (calculatrice.divZero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calculatrice.divZeroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calculatrice.divZeroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calculatrice.divZeroHelper.type ();
  }

}
