package car2.corba.td2.coureur;


/**
* car2/corba/td2/coureur/_THStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TH.idl
* vendredi 17 mai 2013 15 h 20 CEST
*/

public class _THStub extends org.omg.CORBA.portable.ObjectImpl implements car2.corba.td2.coureur.TH
{

  public void inscrire_coureur (car2.corba.td2.coureur.THPackage.Personne C)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("inscrire_coureur", true);
                car2.corba.td2.coureur.THPackage.coureurHelper.write ($out, C);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                inscrire_coureur (C        );
            } finally {
                _releaseReply ($in);
            }
  } // inscrire_coureur

  public void liste_des_coureurs (car2.corba.td2.coureur.THPackage.participantsHolder coureurs)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("liste_des_coureurs", true);
                $in = _invoke ($out);
                coureurs.value = car2.corba.td2.coureur.THPackage.participantsHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                liste_des_coureurs (coureurs        );
            } finally {
                _releaseReply ($in);
            }
  } // liste_des_coureurs

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:car2/corba/td2/coureur/TH:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _THStub
