package car2.corba.td2.coureur;


/**
* car2/corba/td2/coureur/THHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TH.idl
* vendredi 17 mai 2013 15 h 20 CEST
*/

abstract public class THHelper
{
  private static String  _id = "IDL:car2/corba/td2/coureur/TH:1.0";

  public static void insert (org.omg.CORBA.Any a, car2.corba.td2.coureur.TH that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static car2.corba.td2.coureur.TH extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (car2.corba.td2.coureur.THHelper.id (), "TH");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static car2.corba.td2.coureur.TH read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_THStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, car2.corba.td2.coureur.TH value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static car2.corba.td2.coureur.TH narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof car2.corba.td2.coureur.TH)
      return (car2.corba.td2.coureur.TH)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      car2.corba.td2.coureur._THStub stub = new car2.corba.td2.coureur._THStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static car2.corba.td2.coureur.TH unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof car2.corba.td2.coureur.TH)
      return (car2.corba.td2.coureur.TH)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      car2.corba.td2.coureur._THStub stub = new car2.corba.td2.coureur._THStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
