package car2.corba.td2.coureur;

/**
* car2/corba/td2/coureur/THHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TH.idl
* vendredi 17 mai 2013 15 h 20 CEST
*/

public final class THHolder implements org.omg.CORBA.portable.Streamable
{
  public car2.corba.td2.coureur.TH value = null;

  public THHolder ()
  {
  }

  public THHolder (car2.corba.td2.coureur.TH initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = car2.corba.td2.coureur.THHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    car2.corba.td2.coureur.THHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return car2.corba.td2.coureur.THHelper.type ();
  }

}
