package car2.corba.td2.coureur;


/**
* car2/corba/td2/coureur/THOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TH.idl
* vendredi 17 mai 2013 15 h 20 CEST
*/

public interface THOperations 
{
  void inscrire_coureur (car2.corba.td2.coureur.THPackage.Personne C);
  void liste_des_coureurs (car2.corba.td2.coureur.THPackage.participantsHolder coureurs);
} // interface THOperations
