package car2.corba.td2.coureur;


/**
* car2/corba/td2/coureur/THPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TH.idl
* vendredi 17 mai 2013 15 h 20 CEST
*/

public abstract class THPOA extends org.omg.PortableServer.Servant
 implements car2.corba.td2.coureur.THOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("inscrire_coureur", new java.lang.Integer (0));
    _methods.put ("liste_des_coureurs", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // car2/corba/td2/coureur/TH/inscrire_coureur
       {
         car2.corba.td2.coureur.THPackage.Personne C = car2.corba.td2.coureur.THPackage.coureurHelper.read (in);
         this.inscrire_coureur (C);
         out = $rh.createReply();
         break;
       }

       case 1:  // car2/corba/td2/coureur/TH/liste_des_coureurs
       {
         car2.corba.td2.coureur.THPackage.participantsHolder coureurs = new car2.corba.td2.coureur.THPackage.participantsHolder ();
         this.liste_des_coureurs (coureurs);
         out = $rh.createReply();
         car2.corba.td2.coureur.THPackage.participantsHelper.write (out, coureurs.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:car2/corba/td2/coureur/TH:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TH _this() 
  {
    return THHelper.narrow(
    super._this_object());
  }

  public TH _this(org.omg.CORBA.ORB orb) 
  {
    return THHelper.narrow(
    super._this_object(orb));
  }


} // class THPOA
