package car2.corba.job.JobFact;


/**
* car2/corba/job/JobFact/_JobFactoryStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Job.idl
* vendredi 31 mai 2013 14 h 46 CEST
*/

public class _JobFactoryStub extends org.omg.CORBA.portable.ObjectImpl implements car2.corba.job.JobFact.JobFactory
{

  public car2.corba.job.JobProcess createJob (car2.corba.job.Job jd)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createJob", true);
                car2.corba.job.JobDataHelper.write ($out, jd);
                $in = _invoke ($out);
                car2.corba.job.JobProcess $result = car2.corba.job.JobProcessHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createJob (jd        );
            } finally {
                _releaseReply ($in);
            }
  } // createJob

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:car2/corba/job/JobFact/JobFactory:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _JobFactoryStub
