package car2.corba.job.JobFact;


/**
* car2/corba/job/JobFact/JobFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Job.idl
* vendredi 31 mai 2013 14 h 46 CEST
*/

public interface JobFactoryOperations 
{
  car2.corba.job.JobProcess createJob (car2.corba.job.Job jd);
} // interface JobFactoryOperations
