package car2.corba.job.JobFact;


/**
* car2/corba/job/JobFact/JobFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Job.idl
* vendredi 31 mai 2013 14 h 46 CEST
*/

public interface JobFactory extends JobFactoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface JobFactory
