package car2.corba.job.JobFactoryLB;

/**
* car2/corba/job/JobFactoryLB/FactoryLBHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Job.idl
* vendredi 31 mai 2013 14 h 46 CEST
*/

public final class FactoryLBHolder implements org.omg.CORBA.portable.Streamable
{
  public car2.corba.job.JobFactoryLB.FactoryLB value = null;

  public FactoryLBHolder ()
  {
  }

  public FactoryLBHolder (car2.corba.job.JobFactoryLB.FactoryLB initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = car2.corba.job.JobFactoryLB.FactoryLBHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    car2.corba.job.JobFactoryLB.FactoryLBHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return car2.corba.job.JobFactoryLB.FactoryLBHelper.type ();
  }

}
