package car2.corba.job.JobFactoryLB;


/**
* car2/corba/job/JobFactoryLB/FactoryLBPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Job.idl
* vendredi 31 mai 2013 14 h 46 CEST
*/

public abstract class FactoryLBPOA extends org.omg.PortableServer.Servant
 implements car2.corba.job.JobFactoryLB.FactoryLBOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createJob", new java.lang.Integer (0));
    _methods.put ("register", new java.lang.Integer (1));
    _methods.put ("unregister", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // car2/corba/job/JobFactoryLB/FactoryLB/createJob
       {
         car2.corba.job.Job jd = car2.corba.job.JobDataHelper.read (in);
         car2.corba.job.JobProcess $result = null;
         $result = this.createJob (jd);
         out = $rh.createReply();
         car2.corba.job.JobProcessHelper.write (out, $result);
         break;
       }

       case 1:  // car2/corba/job/JobFactoryLB/FactoryLB/register
       {
         car2.corba.job.JobFact.JobFactory jf = car2.corba.job.JobFact.JobFactoryHelper.read (in);
         this.register (jf);
         out = $rh.createReply();
         break;
       }

       case 2:  // car2/corba/job/JobFactoryLB/FactoryLB/unregister
       {
         car2.corba.job.JobFact.JobFactory jf = car2.corba.job.JobFact.JobFactoryHelper.read (in);
         this.unregister (jf);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:car2/corba/job/JobFactoryLB/FactoryLB:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FactoryLB _this() 
  {
    return FactoryLBHelper.narrow(
    super._this_object());
  }

  public FactoryLB _this(org.omg.CORBA.ORB orb) 
  {
    return FactoryLBHelper.narrow(
    super._this_object(orb));
  }


} // class FactoryLBPOA
