package car2.corba.job.JobFactoryLB;


/**
* car2/corba/job/JobFactoryLB/FactoryLBOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Job.idl
* vendredi 31 mai 2013 14 h 46 CEST
*/

public interface FactoryLBOperations 
{
  car2.corba.job.JobProcess createJob (car2.corba.job.Job jd);
  void register (car2.corba.job.JobFact.JobFactory jf);
  void unregister (car2.corba.job.JobFact.JobFactory jf);
} // interface FactoryLBOperations
