package car2.corba.job.JobFactoryLB;


/**
* car2/corba/job/JobFactoryLB/FactoryLB.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Job.idl
* vendredi 31 mai 2013 14 h 46 CEST
*/

public interface FactoryLB extends FactoryLBOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FactoryLB
