package car2.corba.job;


/**
* car2/corba/job/Job.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Job.idl
* vendredi 31 mai 2013 14 h 46 CEST
*/

public final class Job implements org.omg.CORBA.portable.IDLEntity
{
  public String poste = null;
  public double paie = (double)0;

  public Job ()
  {
  } // ctor

  public Job (String _poste, double _paie)
  {
    poste = _poste;
    paie = _paie;
  } // ctor

} // class Job
