package car2.corba.job;

/**
* car2/corba/job/JobHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Job.idl
* vendredi 31 mai 2013 14 h 46 CEST
*/

public final class JobHolder implements org.omg.CORBA.portable.Streamable
{
  public car2.corba.job.Job value = null;

  public JobHolder ()
  {
  }

  public JobHolder (car2.corba.job.Job initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = car2.corba.job.JobHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    car2.corba.job.JobHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return car2.corba.job.JobHelper.type ();
  }

}
