package car2.corba.job;


/**
* car2/corba/job/JobProcessOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Job.idl
* vendredi 31 mai 2013 14 h 46 CEST
*/

public interface JobProcessOperations 
{
  void run ();
} // interface JobProcessOperations
