package car2.corba.job;

/**
* car2/corba/job/JobProcessHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Job.idl
* vendredi 31 mai 2013 14 h 46 CEST
*/

public final class JobProcessHolder implements org.omg.CORBA.portable.Streamable
{
  public car2.corba.job.JobProcess value = null;

  public JobProcessHolder ()
  {
  }

  public JobProcessHolder (car2.corba.job.JobProcess initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = car2.corba.job.JobProcessHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    car2.corba.job.JobProcessHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return car2.corba.job.JobProcessHelper.type ();
  }

}
