package rdv;


/**
* rdv/_FactRdvStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rdv.idl
* mardi 11 juin 2013 13 h 21 CEST
*/

public class _FactRdvStub extends org.omg.CORBA.portable.ObjectImpl implements rdv.FactRdv
{

  public rdv.RdvItf creer (int nombre, String nom)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("creer", true);
                $out.write_long (nombre);
                $out.write_string (nom);
                $in = _invoke ($out);
                rdv.RdvItf $result = rdv.RdvItfHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return creer (nombre, nom        );
            } finally {
                _releaseReply ($in);
            }
  } // creer

  public rdv.RdvItf chercher (String nom)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("chercher", true);
                $out.write_string (nom);
                $in = _invoke ($out);
                rdv.RdvItf $result = rdv.RdvItfHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return chercher (nom        );
            } finally {
                _releaseReply ($in);
            }
  } // chercher

  public rdv.RdvItf[] getRdvs ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRdvs", true);
                $in = _invoke ($out);
                rdv.RdvItf $result[] = rdv.rdvsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRdvs (        );
            } finally {
                _releaseReply ($in);
            }
  } // getRdvs

  public int getNb ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getNb", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getNb (        );
            } finally {
                _releaseReply ($in);
            }
  } // getNb

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:rdv/FactRdv:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _FactRdvStub
