package rdv;


/**
* rdv/FactRdvPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rdv.idl
* mardi 11 juin 2013 13 h 21 CEST
*/

public abstract class FactRdvPOA extends org.omg.PortableServer.Servant
 implements rdv.FactRdvOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("creer", new java.lang.Integer (0));
    _methods.put ("chercher", new java.lang.Integer (1));
    _methods.put ("getRdvs", new java.lang.Integer (2));
    _methods.put ("getNb", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // rdv/FactRdv/creer
       {
         int nombre = in.read_long ();
         String nom = in.read_string ();
         rdv.RdvItf $result = null;
         $result = this.creer (nombre, nom);
         out = $rh.createReply();
         rdv.RdvItfHelper.write (out, $result);
         break;
       }

       case 1:  // rdv/FactRdv/chercher
       {
         String nom = in.read_string ();
         rdv.RdvItf $result = null;
         $result = this.chercher (nom);
         out = $rh.createReply();
         rdv.RdvItfHelper.write (out, $result);
         break;
       }

       case 2:  // rdv/FactRdv/getRdvs
       {
         rdv.RdvItf $result[] = null;
         $result = this.getRdvs ();
         out = $rh.createReply();
         rdv.rdvsHelper.write (out, $result);
         break;
       }

       case 3:  // rdv/FactRdv/getNb
       {
         int $result = (int)0;
         $result = this.getNb ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:rdv/FactRdv:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FactRdv _this() 
  {
    return FactRdvHelper.narrow(
    super._this_object());
  }

  public FactRdv _this(org.omg.CORBA.ORB orb) 
  {
    return FactRdvHelper.narrow(
    super._this_object(orb));
  }


} // class FactRdvPOA
