package rdv;

/**
* rdv/FactRdvHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rdv.idl
* mardi 11 juin 2013 13 h 21 CEST
*/

public final class FactRdvHolder implements org.omg.CORBA.portable.Streamable
{
  public rdv.FactRdv value = null;

  public FactRdvHolder ()
  {
  }

  public FactRdvHolder (rdv.FactRdv initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = rdv.FactRdvHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    rdv.FactRdvHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return rdv.FactRdvHelper.type ();
  }

}
