package rdv;


/**
* rdv/FactRdvOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rdv.idl
* mardi 11 juin 2013 13 h 21 CEST
*/

public interface FactRdvOperations 
{
  rdv.RdvItf creer (int nombre, String nom);
  rdv.RdvItf chercher (String nom);
  rdv.RdvItf[] getRdvs ();
  int getNb ();
} // interface FactRdvOperations
