package rdv;


/**
* rdv/FactRdvHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rdv.idl
* mardi 11 juin 2013 13 h 21 CEST
*/

abstract public class FactRdvHelper
{
  private static String  _id = "IDL:rdv/FactRdv:1.0";

  public static void insert (org.omg.CORBA.Any a, rdv.FactRdv that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static rdv.FactRdv extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (rdv.FactRdvHelper.id (), "FactRdv");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static rdv.FactRdv read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FactRdvStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, rdv.FactRdv value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static rdv.FactRdv narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof rdv.FactRdv)
      return (rdv.FactRdv)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      rdv._FactRdvStub stub = new rdv._FactRdvStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static rdv.FactRdv unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof rdv.FactRdv)
      return (rdv.FactRdv)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      rdv._FactRdvStub stub = new rdv._FactRdvStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
