package rdv;

/**
* rdv/ParticipantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rdv.idl
* mardi 11 juin 2013 13 h 21 CEST
*/

public final class ParticipantHolder implements org.omg.CORBA.portable.Streamable
{
  public rdv.Participant value = null;

  public ParticipantHolder ()
  {
  }

  public ParticipantHolder (rdv.Participant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = rdv.ParticipantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    rdv.ParticipantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return rdv.ParticipantHelper.type ();
  }

}
