package rdv;


/**
* rdv/ParticipantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rdv.idl
* mardi 11 juin 2013 13 h 21 CEST
*/

public interface ParticipantOperations 
{
  void rdvTermine (String nom);
} // interface ParticipantOperations
