package rdv;


/**
* rdv/RdvItfOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rdv.idl
* mardi 11 juin 2013 13 h 21 CEST
*/

public interface RdvItfOperations 
{
  void rejoindre (rdv.Participant participant);
  String getNom ();
  int getNombre ();
} // interface RdvItfOperations
