package rdv;


/**
* rdv/RdvItfPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rdv.idl
* mardi 11 juin 2013 13 h 21 CEST
*/

public abstract class RdvItfPOA extends org.omg.PortableServer.Servant
 implements rdv.RdvItfOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("rejoindre", new java.lang.Integer (0));
    _methods.put ("getNom", new java.lang.Integer (1));
    _methods.put ("getNombre", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // rdv/RdvItf/rejoindre
       {
         rdv.Participant participant = rdv.ParticipantHelper.read (in);
         this.rejoindre (participant);
         out = $rh.createReply();
         break;
       }

       case 1:  // rdv/RdvItf/getNom
       {
         String $result = null;
         $result = this.getNom ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // rdv/RdvItf/getNombre
       {
         int $result = (int)0;
         $result = this.getNombre ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:rdv/RdvItf:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RdvItf _this() 
  {
    return RdvItfHelper.narrow(
    super._this_object());
  }

  public RdvItf _this(org.omg.CORBA.ORB orb) 
  {
    return RdvItfHelper.narrow(
    super._this_object(orb));
  }


} // class RdvItfPOA
