package rdv;

/**
* rdv/RdvItfHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rdv.idl
* mardi 11 juin 2013 13 h 21 CEST
*/

public final class RdvItfHolder implements org.omg.CORBA.portable.Streamable
{
  public rdv.RdvItf value = null;

  public RdvItfHolder ()
  {
  }

  public RdvItfHolder (rdv.RdvItf initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = rdv.RdvItfHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    rdv.RdvItfHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return rdv.RdvItfHelper.type ();
  }

}
