package car2.corba.td2.coureur.THPackage;


/**
* car2/corba/td2/coureur/THPackage/participantsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TH.idl
* vendredi 17 mai 2013 15 h 20 CEST
*/

public final class participantsHolder implements org.omg.CORBA.portable.Streamable
{
  public car2.corba.td2.coureur.THPackage.Personne value[] = null;

  public participantsHolder ()
  {
  }

  public participantsHolder (car2.corba.td2.coureur.THPackage.Personne[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = car2.corba.td2.coureur.THPackage.participantsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    car2.corba.td2.coureur.THPackage.participantsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return car2.corba.td2.coureur.THPackage.participantsHelper.type ();
  }

}
