package car2.corba.td2.coureur.THPackage;


/**
* car2/corba/td2/coureur/THPackage/PersonneHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TH.idl
* vendredi 17 mai 2013 15 h 20 CEST
*/

abstract public class PersonneHelper
{
  private static String  _id = "IDL:car2/corba/td2/coureur/TH/Personne:1.0";

  public static void insert (org.omg.CORBA.Any a, car2.corba.td2.coureur.THPackage.Personne that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static car2.corba.td2.coureur.THPackage.Personne extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "nom",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "prenom",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (car2.corba.td2.coureur.THPackage.PersonneHelper.id (), "Personne", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static car2.corba.td2.coureur.THPackage.Personne read (org.omg.CORBA.portable.InputStream istream)
  {
    car2.corba.td2.coureur.THPackage.Personne value = new car2.corba.td2.coureur.THPackage.Personne ();
    value.nom = istream.read_string ();
    value.prenom = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, car2.corba.td2.coureur.THPackage.Personne value)
  {
    ostream.write_string (value.nom);
    ostream.write_string (value.prenom);
  }

}
